apiVersion: v1
kind: PersistentVolume
metadata:
  name: collectory-mysql-volume
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClassName }}
  csi:
    driver: {{ .Values.csi.driver }}
    volumeHandle: {{ .Values.csi.volumeHandle }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: collectory-mysql-claim
spec:
  volumeName: collectory-mysql-volume
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 25Gi
