cassandra:
  fullnameOverride: biocache-cassandra

  extraEnvVars:
    - name: CASSANDRA_AUTHENTICATOR
      value: AllowAllAuthenticator
    - name: CASSANDRA_AUTHORIZER
      value: AllowAllAuthorizer

  image:
    registry: docker.io
    repository: bitnami/cassandra
    tag: 3.11.13

  resources:
    limits:
      cpu: "2000m"
      memory: "8Gi"
    requests:
      cpu: "1000m"
      memory: "4Gi"

  replicaCount: 1
  heap: "2g"

  networkPolicy:
    enabled: true
    allowExternal: false
    explicitNamespacesSelector:
      matchLabels:
        biocache-cassandra-network: "true"

  persistence:
    existingClaim: "biocache-cassandra-claim"
    mountPath: /data/cassandra/
    subPathExpr: biocache-cassandra/$(MY_POD_NAME)
    enabled: true
    storageClass: efs-sc
    accessMode: ReadWriteMany
    size: 100Gi
