apiVersion: apps/v1
kind: Deployment
metadata:
  name: biocache-service
  labels:
    app: biocache-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: biocache-service
  template:
    metadata:
      labels:
        app: biocache-service
        solr-network: "true"
        biocache-cassandra-network: "true"
    spec:
      containers:
        - name: biocache-service
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: {{ .Values.javaOpts }}
            - name: SERVER_PORT
              value: {{ .Values.serverPort }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          volumeMounts:
            - name: biocache-config
              mountPath: /data/biocache/config/
      volumes:
        - name: biocache-config
          configMap:
            name: biocache-config
      restartPolicy: Always
