apiVersion: v1
kind: Service
metadata:
  name: biocache-service
  labels:
    app: biocache-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: "web-access-biocache-service-https"
      port: 443
      targetPort: 8080
  selector:
    app: biocache-service