apiVersion: apps/v1
kind: Deployment
metadata:
  name: bie-index
  labels:
    app: bie-index
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bie-index
  template:
    metadata:
      labels:
        bie-index-mysql-network: "true"
        app: bie-index
    spec:
      containers:
        - name: bie-index
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: {{ .Values.javaOpts }}
            - name: SERVER_PORT
              value: {{ .Values.serverPort }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          volumeMounts:
            - name: bie-index-config
              mountPath: /data/bie-index/config/
      volumes:
        - name: bie-index-config
          configMap:
            name: bie-index-config
      restartPolicy: Always

