apiVersion: apps/v1
kind: Deployment
metadata:
  name: bie-index
  labels:
    app: bie-index
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bie-index
  template:
    metadata:
      labels:
        bie-index-mysql-network: "true"
        app: bie-index
    spec:
      containers:
        - name: bie-index
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Dserver.port=8080 -Djava.awt.headless=true -Xmx4g -Xms2g -Dlog4j2.formatMsgNoLookups=true"
            - name: SERVER_PORT
              value: "8080"
          resources:
            limits:
              cpu: "4000m"
              memory: "8Gi"
            requests:
              cpu: "2000m"
              memory: "4Gi"
          volumeMounts:
            - name: bie-index-config
              mountPath: /data/bie-index/config/
      volumes:
        - name: bie-index-config
          configMap:
            name: bie-index-config
      restartPolicy: Always

