apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensitive-data-service
  labels:
    app: sensitive-data-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sensitive-data-service
  template:
    metadata:
      labels:
        app: sensitive-data-service
    spec:
      containers:
        - name: sensitive-data-service
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 9179
          resources:
            limits:
              cpu: "2000m"
              memory: "4Gi"
            requests:
              cpu: "1000m"
              memory: "2Gi"
