apiVersion: apps/v1
kind: Deployment
metadata:
  name: species-lists
  labels:
    app: species-lists
spec:
  replicas: 1
  selector:
    matchLabels:
      app: species-lists
  template:
    metadata:
      labels:
        species-lists-mysql-network: "true"
        app: species-lists
    spec:
      containers:
        - name: species-lists
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Dserver.port=8080 -Djava.awt.headless=true -Xmx4g -Xms2g -Dlog4j2.formatMsgNoLookups=true"
            - name: SERVER_PORT
              value: "8080"
          resources:
            limits:
              cpu: "4000m"
              memory: "8Gi"
            requests:
              cpu: "2000m"
              memory: "4Gi"
          volumeMounts:
            - name: species-lists-config
              mountPath: /data/specieslist-webapp/config/
      volumes:
        - name: species-lists-config
          configMap:
            name: species-lists-config
      restartPolicy: Always

