apiVersion: apps/v1
kind: Deployment
metadata:
  name: species-lists
  labels:
    app: species-lists
spec:
  replicas: 1
  selector:
    matchLabels:
      app: species-lists
  template:
    metadata:
      labels:
        species-lists-mysql-network: "true"
        app: species-lists
    spec:
      containers:
        - name: species-lists
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: {{ .Values.javaOpts }}
            - name: SERVER_PORT
              value: {{ .Values.serverPort }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          volumeMounts:
            - name: species-lists-config
              mountPath: /data/specieslist-webapp/config/
      volumes:
        - name: species-lists-config
          configMap:
            name: species-lists-config
      restartPolicy: Always

