apiVersion: v1
kind: Service
metadata:
  name: species-lists
  labels:
    app: species-lists
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: "web-access-species-lists-https"
      port: 443
      targetPort: 8080
  selector:
    app: species-lists