image:
  repository: atlasoflivingaustralia/lists-service
  tag: latest
  pullPolicy: Always
dnsName: lists-ws.dev.ala.org.au
replicaCount: 2
serverPort: 8080
javaOpts: "-Djava.awt.headless=true -Xmx2g -Xms1g -Dlog4j2.formatMsgNoLookups=true"
resources:
  limits:
    cpu: "2000m"
    memory: "4Gi"
  requests:
    cpu: "1000m"
    memory: "2Gi"
