apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-airflow-triggerer-efs
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClassName }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.csi.volumeHandle }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-airflow-triggerer-0
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClassName }}
  volumeName: logs-airflow-triggerer-efs
  resources:
    requests:
      storage: 50Gi