apiVersion: apps/v1
kind: Deployment
metadata:
  name: publishing-service
  labels:
    app: publishing-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: publishing-service
  template:
    metadata:
      labels:
        app: publishing-service
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: publishing-service
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: SERVER_PORT
              value: "{{ .Values.serverPort }}"
          resources:
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
          volumeMounts:
            - name: publishing-service-config
              mountPath: /data/publishing-service/config/
      volumes:
        - name: publishing-service-config
          configMap:
            name: publishing-service-config
      restartPolicy: Always

