apiVersion: v1
kind: Service
metadata:
  name: publishing-service
  labels:
    app: publishing-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: "web-access-publishing-service-https"
      port: 443
      targetPort: 5000
  selector:
    app: publishing-service