apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-matching-service
  labels:
    app: name-matching-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: name-matching-service
  template:
    metadata:
      labels:
        app: name-matching-service
    spec:
      containers:
        - name: name-matching-service
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 9179
          resources:
            limits:
              cpu: "2000m"
              memory: "4Gi"
            requests:
              cpu: "1000m"
              memory: "2Gi"
