apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-matching-service
  labels:
    app: name-matching-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: name-matching-service
  template:
    metadata:
      labels:
        app: name-matching-service
    spec:
      containers:
        - name: name-matching-service
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 9179
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
