apiVersion: v1
kind: Service
metadata:
  name: name-matching-service
  labels:
    app: name-matching-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: "web-access-name-service-https"
      port: 443
      targetPort: 9179
  selector:
    app: name-matching-service