apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-data-efs
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-05b4e90dde1fc0275::fsap-0d8f50eeb707be580
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: living-atlas-airflow-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: airflow-data-efs
  resources:
    requests:
      storage: 25Gi
