apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-data-efs
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClassName }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.csi.volumeHandle }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: living-atlas-airflow-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClassName }}
  volumeName: airflow-data-efs
  resources:
    requests:
      storage: 25Gi
