apiVersion: v1
kind: Service
metadata:
  name: lists-api
  labels:
    app: lists-api
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: "web-access-species-lists-https"
      port: 443
      targetPort: 8080
  selector:
    app: lists-api