apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        elasticsearch-network: "true"
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
          - name: discovery.type
            value: single-node
          - name: node.name
            value: elasticsearch
          - name: xpack.security.enabled
            value: "false"
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://elasticsearch:9200
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          resources:
            limits:
              cpu: "2000m"
              memory: "4Gi"
            requests:
              cpu: "1000m"
              memory: "2Gi"
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-claim
              subPath: elasticsearch/data
      volumes:
        - name: elasticsearch-claim
          persistentVolumeClaim:
            claimName: elasticsearch-claim
      restartPolicy: Always