apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: "web-access-elasticsearch-https"
      port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch

