apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ala-hub
  labels:
    app: ala-hub
  annotations:
    {{- if .Values.dnsName }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.dnsName }}
    {{- end }}
{{ toYaml .Values.ingressAnnotations | indent 4 }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ala-hub
                port:
                  number: 443
