apiVersion: apps/v1
kind: Deployment
metadata:
  name: lists-service
  labels:
    app: lists-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: lists-service
  template:
    metadata:
      labels:
        species-lists-mysql-network: "true"
        app: lists-service
    spec:
      containers:
        - name: lists-service
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: {{ .Values.javaOpts }}
            - name: SERVER_PORT
              value: {{ .Values.serverPort }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          volumeMounts:
            - name: lists-service-config
              mountPath: /data/lists-service/config/
      volumes:
        - name: lists-service-config
          configMap:
            name: lists-service-config
      restartPolicy: Always

