apiVersion: apps/v1
kind: Deployment
metadata:
  name: collectory
  labels:
    app: collectory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collectory
  template:
    metadata:
      labels:
        collectory-mysql-network: "true"
        app: collectory
    spec:
      containers:
        - name: collectory
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Dserver.port=8080 -Djava.awt.headless=true -Xmx2g -Xms1g -Dlog4j2.formatMsgNoLookups=true"
            - name: SERVER_PORT
              value: "8080"
          resources:
            limits:
              cpu: "2000m"
              memory: "4Gi"
            requests:
              cpu: "1000m"
              memory: "2Gi"
          volumeMounts:
            - name: collectory-config
              mountPath: /data/collectory/config/
            - mountPath: /data/collectory/data
              name: collectory-claim
              subPath: collectory/data
            - mountPath: /data/collectory/upload
              name: collectory-claim
              subPath: collectory/upload
      volumes:
        - name: collectory-claim
          persistentVolumeClaim:
            claimName: collectory-claim
        - name: collectory-config
          configMap:
            name: collectory-config
      restartPolicy: Always

