apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: collectory
  labels:
    app: collectory
  annotations:
{{ toYaml .Values.ingressAnnotations | indent 4 }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: collectory
                port:
                  number: 443
