apiVersion: v1
kind: Service
metadata:
  name: collectory
  labels:
    app: collectory
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: "web-access-collectory-https"
      port: 443
      targetPort: 8080
  selector:
    app: collectory

