apiVersion: v2
name: solr
description: SOLR cloud cluster with zookeeper for biocache and bie
version: 0.1.0
dependencies:
  - name: solr
    version: "7.5.9"
    repository: "https://charts.bitnami.com/bitnami"