solr:
  image:
    registry: docker.io
    repository: atlasoflivingaustralia/solr8-jts
    tag: bitnami-8.11.2
    pullPolicy: IfNotPresent
    debug: true

  global:
    compatibility:
      openshift:
        adaptSecurityContext: disabled

  auth:
    enabled: false
  authorization:
    enabled: false

  extraEnvVars:
    - name: "SOLR_ULIMIT_CHECKS"
      value: "65000"
    - name: "SOLR_DATA_HOME"
      value: "/bitnami/solr"

  service:
    type: ClusterIP

  resources:
    limits:
      cpu: "4000m"
      memory: "16Gi"
    requests:
      cpu: "2000m"
      memory: "12Gi"

  startupProbe:
    enabled: true
  readinessProbe:
    enabled: true
  livenessProbe:
    enabled: true

  replicaCount: 4
  heap: "8g"

  networkPolicy:
    enabled: true
    allowExternal: false
    explicitNamespacesSelector:
      matchLabels:
        solr-network: "true"

  persistence:
    existingClaim: solr-claim
    mountPath: /bitnami/solr
    subPathExpr: solr/$(MY_POD_NAME)
    enabled: true
    accessMode: ReadWriteMany
    size: 100Gi

  solrOpts: "-Dsolr.cloud=true"

  zookeeper:
    enabled: false

  externalZookeeper:
    servers:
      - "zookeeper-0.zookeeper-headless.default.svc.cluster.local:2181,zookeeper-1.zookeeper-headless.default.svc.cluster.local:2181,zookeeper-2.zookeeper-headless.default.svc.cluster.local:2181"

  ingress:
    enabled: true
    hostname: ""
    extraRules:
    - http:
        paths:
          - backend:
              service:
                name: solr
                port:
                  number: 8983
            path: /
            pathType: Prefix
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/target-type: ip # instance doesn't work with Fargate. See https://docs.aws.amazon.com/eks/latest/userguide/fargate.html#fargate-considerations
      alb.ingress.kubernetes.io/success-codes: 200,302
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTP": 8983}]'
      alb.ingress.kubernetes.io/inbound-cidrs: 10.0.0.0/20
      alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=ala-alb-access-logs

metrics:
  enabled: true

diagnosticMode:
  enabled: true
