image:
  repository: atlasoflivingaustralia/ala-namematching-service
  tag: v20210811-3
dnsName: namematching-ws.dev.ala.org.au
replicaCount: 2
serverPort: 8080
javaOpts: "-Dserver.port=8080 -Djava.awt.headless=true -Xmx2g -Xms1g -Dlog4j2.formatMsgNoLookups=true"
resources:
  limits:
    cpu: "2000m"
    memory: "4Gi"
  requests:
    cpu: "1000m"
    memory: "2Gi"